In [1]:
import torch
import numpy as np

In [4]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
# 可使用 dtype 來設定數據類型
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [6]:
# 建立全為 0 的張量
torch.zeros([2, 2])


tensor([[0., 0.],
        [0., 0.]])

In [7]:
# 建立全為 1 的張量
torch.ones([2, 2])

tensor([[1., 1.],
        [1., 1.]])

In [11]:
print(torch.cuda.is_available())

False


In [9]:
import torch
import math

print(torch.backends.mps.is_available())
# True
print(torch.backends.mps.is_built())
# True


True
True


In [15]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
    t1 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
    numpy1 = t1.numpy()
    print("numpy1:", numpy1)
    print("type:", type(numpy1))
else:
    print ("MPS device not found.")


tensor([1.], device='mps:0')
numpy1: [[1. 2.]
 [3. 4.]
 [5. 6.]]
type: <class 'numpy.ndarray'>


In [16]:
numpy2 = np.array([[1, 2, 3], [4, 5, 6]])

# 第一種
tensor1 = torch.tensor(numpy2)
print("dtype:", tensor1.dtype)

# 第二種
tensor2 = torch.Tensor(numpy2)
print("dtype:", tensor2.dtype)

# 第三種
tensor3 = torch.as_tensor(numpy2)
print("dtype:", tensor3.dtype)

# 第四種
tensor4 = torch.from_numpy(numpy2)
print("dtype:", tensor4.dtype)

dtype: torch.int64
dtype: torch.float32
dtype: torch.int64
dtype: torch.int64


In [17]:
# 建立 Tensor 並設定 requires_grad 為 True
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, requires_grad=True)
# 建立隨機數值的 Tensor 並設定 requires_grad 為 True
torch.randn(2, 3, requires_grad=True)

tensor([[ 0.9727, -0.4440,  1.1279],
        [ 0.2674,  1.4145, -0.7083]], requires_grad=True)

In [19]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)
# 計算梯度
c.backward()
# 查看 x 的梯度值
print(x.grad)
# 設定 detach()
d = x.detach()
# 查看是否追蹤 d 的梯度計算及數值
print("d requires grad:", d. requires_grad)
print("d grad:", d)

tensor([[ 0.3271, -1.5822,  0.4154],
        [ 1.7853, -0.2583, -1.1958]])
d requires grad: False
d grad: tensor([[ 0.6844,  0.4112, -0.3473],
        [ 0.4151,  1.0079, -1.4076]])
